version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: parqueo_db
      POSTGRES_USER: marvin
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"

  app:
    build: .
    command: python parqueo.py --db-user=marvin --db-pass=12345 --db-name=parqueo_db  # Proporcionar valores aquí
    environment:
      DB_HOST: db
    depends_on:
      - db

